[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_program = "D3jAcqXfbzCFWK69m4ysWKEtTowuSFf3b33dAJo3k8DW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8890"
wallet = "~/.config/solana/id.json"
timeout = "120s"

[test.validator]
url = "http://127.0.0.1:8890"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
