-- Add totalPnL and tradesExecuted fields to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totalPnL" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tradesExecuted" INTEGER NOT NULL DEFAULT 0;

